### ISSUE TITLE
中文不显示

### ISSUE THREAD

**Issue by zhouLion** [ly2013203742/arcgisapi#1]
![image](https://user-images.githubusercontent.com/19882767/56454653-c8f86400-6386-11e9-8609-5404160685a6.png)
使用你提供的fonts文件夹下的发的服务，但是中文全都显示不出来，请问是什么原因呢？

**Comment by swaggyPYang** [comment]
我提供的字体都是外语字体，没有中文字体，我取名叫lisu了而已，要显示中文，你还是自己转换一下字体吧，https://www.jianshu.com/p/12c3c8fe05fa
